"""
Tests for the guardrail catalogue and the policy corpus it ships.

Two layers, mirroring test_detections.py:

  * Unit tests for the derivation rules, covering the shapes that decide a
    policy's type and service tags.
  * A corpus test that folds the contract over every policy the repository
    ships, so a policy that is unnamed, unparseable or unreachable by URL fails
    at PR time rather than as a gap in the library after merge.

The corpus layer is what makes the catalogue self-maintaining. Adding a policy
document without an entry in MANIFEST.py, or an entry naming a file that is not
there, fails here; nothing has to be regenerated by hand.
"""

import json
import os
import re
import sys
from pathlib import Path

from django.test import SimpleTestCase

# backend/apps/guardrails/tests/test_guardrails.py -> repo root is parents[4].
_REPO_ROOT = Path(__file__).resolve().parents[4]


def _package_parent() -> Path:
    """
    Return the directory that must be on sys.path to import `guardrails`.

    Prefers GUARDRAILS_BASE_DIR (Docker, where the library is mounted outside
    the repository) and falls back to the repository root, so the suite runs
    locally with no environment set up.
    """
    env_dir = os.environ.get("GUARDRAILS_BASE_DIR", "")
    if env_dir and Path(env_dir).is_dir():
        return Path(env_dir).resolve().parent
    return _REPO_ROOT


_PARENT = str(_package_parent())
if _PARENT not in sys.path:
    sys.path.insert(0, _PARENT)

from guardrails.MANIFEST import POLICIES, SOURCES  # noqa: E402
from guardrails.registry import ALL_SERVICES, _derive, _slug, discover  # noqa: E402

_URL_SAFE = re.compile(r"[a-z0-9-]+")
_POLICIES_DIR = _package_parent() / "guardrails" / "policies"


class DerivationTests(SimpleTestCase):
    """The rules that read a policy's type and services out of its body."""

    def test_principal_marks_a_resource_control_policy(self):
        """An SCP cannot name a principal, so Principal identifies an RCP."""
        kind, _ = _derive({"Statement": [{"Effect": "Deny", "Principal": "*", "Action": "s3:*"}]})
        self.assertEqual(kind, "RCP")

    def test_absent_principal_marks_a_service_control_policy(self):
        kind, _ = _derive({"Statement": [{"Effect": "Deny", "Action": "s3:*"}]})
        self.assertEqual(kind, "SCP")

    def test_single_statement_object_is_accepted(self):
        """Statement is allowed to be one object rather than a list."""
        kind, services = _derive({"Statement": {"Effect": "Deny", "Action": "kms:Decrypt"}})
        self.assertEqual(kind, "SCP")
        self.assertEqual(services, ["KMS"])

    def test_action_prefixes_map_to_display_labels(self):
        _, services = _derive({"Statement": [{"Action": ["elasticmapreduce:RunJobFlow", "ec2:RunInstances"]}]})
        self.assertEqual(services, ["EC2", "EMR"])

    def test_duplicate_labels_collapse(self):
        """Distinct prefixes sharing a display name are listed once."""
        _, services = _derive({"Statement": [{"Action": ["cognito-idp:DeleteUserPool", "cognito-identity:DeleteIdentityPool"]}]})
        self.assertEqual(services, ["Cognito"])

    def test_wildcard_action_tags_all_services(self):
        _, services = _derive({"Statement": [{"Action": "*"}]})
        self.assertEqual(services, [ALL_SERVICES])

    def test_notaction_tags_all_services(self):
        """
        NotAction denies everything except what it lists, so the named services
        are the exemptions. Tagging them would label the policy with the only
        services it does not constrain.
        """
        _, services = _derive({"Statement": [{"Effect": "Deny", "NotAction": ["iam:Get*"]}]})
        self.assertEqual(services, [ALL_SERVICES])

    def test_slug_strips_characters_that_need_url_encoding(self):
        self.assertEqual(
            _slug("S3-Deny-users-from-modifying-S3-Block-Public-Access-(Account-Level).json"),
            "s3-deny-users-from-modifying-s3-block-public-access-account-level",
        )


class CorpusTests(SimpleTestCase):
    """Contract checks folded over every policy the repository ships."""

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.catalogue = discover()

    def test_manifest_and_directory_agree(self):
        """
        Every document has an authored purpose and every entry has a document.

        This is the check that replaces regenerating a manifest by hand: the
        two can no longer drift without failing here.
        """
        on_disk = {p.name for p in _POLICIES_DIR.iterdir() if p.suffix == ".json"}
        self.assertEqual(
            on_disk - POLICIES.keys(), set(), "policy files with no purpose authored in MANIFEST.py"
        )
        self.assertEqual(
            POLICIES.keys() - on_disk, set(), "MANIFEST.py entries with no policy file on disk"
        )

    def test_catalogue_covers_every_policy(self):
        self.assertEqual(len(self.catalogue), len(POLICIES))

    def test_every_policy_is_a_parseable_policy_document(self):
        for entry in self.catalogue:
            with self.subTest(policy=entry["file"]):
                document = json.loads(entry["code"])
                self.assertIn("Statement", document)
                statements = document["Statement"]
                if isinstance(statements, dict):
                    statements = [statements]
                self.assertTrue(statements, "policy has no statements")

    def test_ids_are_unique_and_url_safe(self):
        """Ids are route segments, so they must survive a URL without encoding."""
        ids = [entry["id"] for entry in self.catalogue]
        self.assertEqual(len(set(ids)), len(ids), "duplicate catalogue id")
        for entry_id in ids:
            with self.subTest(id=entry_id):
                self.assertRegex(entry_id, _URL_SAFE)

    def test_type_matches_the_presence_of_a_principal(self):
        for entry in self.catalogue:
            with self.subTest(policy=entry["file"]):
                document = json.loads(entry["code"])
                statements = document["Statement"]
                if isinstance(statements, dict):
                    statements = [statements]
                expected = "RCP" if any("Principal" in s for s in statements) else "SCP"
                self.assertEqual(entry["type"], expected)

    def test_every_entry_is_described_and_attributed(self):
        for entry in self.catalogue:
            with self.subTest(policy=entry["file"]):
                self.assertTrue(entry["purpose"].strip(), "empty purpose")
                self.assertTrue(entry["services"], "no service tags")
                self.assertTrue(entry["source"]["label"].strip(), "empty source label")

    def test_every_source_links_to_its_upstream_repository(self):
        """A reader must be able to verify a policy against its original."""
        for key, source in SOURCES.items():
            with self.subTest(source=key):
                self.assertTrue(source["url"].startswith("https://"))
