name: mayatrail-aws-credential-access-secretsmanager-batch-retrieve-secrets
runtime: python
description: Infrastructure for the aws_credential_access_secretsmanager_batch_retrieve_secrets atomic emulation.
