# Generated by Django 5.0.6 on 2026-09-16 22:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='info', max_length=16)),
                ('event', models.CharField(choices=[('stack.deployed', 'Stack Deployed'), ('stack.destroyed', 'Stack Destroyed'), ('emulation.started', 'Emulation Started'), ('emulation.completed', 'Emulation Completed'), ('emulation.failed', 'Emulation Failed'), ('stack.failed', 'Stack Failed'), ('workflow.started', 'Workflow Started'), ('workflow.completed', 'Workflow Completed'), ('workflow.failed', 'Workflow Failed'), ('playbook.command', 'Playbook Command Run')], db_index=True, help_text='Machine-readable event identifier.', max_length=64)),
                ('message', models.TextField(help_text='Human-readable description of the event.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'log entry',
                'verbose_name_plural': 'log entries',
                'db_table': 'log_entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
