# Generated by Django 5.0.6 on 2026-09-16 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0002_initial'),
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='User who caused this event, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logentry',
            name='stack',
            field=models.ForeignKey(blank=True, help_text='Stack this event relates to, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='infrastructure.stack'),
        ),
    ]
