# Generated by Django 5.0.6 on 2026-09-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='event',
            field=models.CharField(choices=[('stack.deployed', 'Stack Deployed'), ('stack.destroyed', 'Stack Destroyed'), ('emulation.started', 'Emulation Started'), ('emulation.completed', 'Emulation Completed'), ('emulation.failed', 'Emulation Failed'), ('stack.failed', 'Stack Failed'), ('workflow.started', 'Workflow Started'), ('workflow.completed', 'Workflow Completed'), ('workflow.failed', 'Workflow Failed'), ('workflow.archived', 'Workflow Archived'), ('workflow.restored', 'Workflow Restored'), ('playbook.command', 'Playbook Command Run')], db_index=True, help_text='Machine-readable event identifier.', max_length=64),
        ),
    ]
