# Generated by Django 5.0.6 on 2026-09-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_logentry_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='event',
            field=models.CharField(choices=[('stack.deployed', 'Stack Deployed'), ('stack.destroyed', 'Stack Destroyed'), ('emulation.started', 'Emulation Started'), ('emulation.completed', 'Emulation Completed'), ('emulation.failed', 'Emulation Failed'), ('stack.failed', 'Stack Failed'), ('workflow.started', 'Workflow Started'), ('workflow.completed', 'Workflow Completed'), ('workflow.failed', 'Workflow Failed'), ('workflow.archived', 'Workflow Archived'), ('workflow.restored', 'Workflow Restored'), ('playbook.command', 'Playbook Command Run'), ('scan.started', 'Attack Graph Scan Started'), ('scan.completed', 'Attack Graph Scan Completed'), ('scan.failed', 'Attack Graph Scan Failed')], db_index=True, help_text='Machine-readable event identifier.', max_length=64),
        ),
    ]
