# Generated by Django 5.0.6 on 2026-09-21 19:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('task_id', models.CharField(blank=True, help_text='Celery task id, for tracing a scan that stops reporting.', max_length=255)),
                ('result', models.JSONField(blank=True, help_text='The serialized result envelope (see envelope.py), once complete.', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Human-readable failure reason, shown to the user verbatim.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='UTC timestamp when the Celery task began executing.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='UTC timestamp when the scan reached a terminal status.', null=True)),
                ('user', models.ForeignKey(help_text='User who triggered this scan; the audit role assumed is theirs.', on_delete=django.db.models.deletion.CASCADE, related_name='scout_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'scout scan',
                'verbose_name_plural': 'scout scans',
                'db_table': 'scout_scans',
                'ordering': ['-created_at'],
            },
        ),
    ]
