# Generated by Django 5.0.6 on 2026-09-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attack_graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutscan',
            name='graph',
            field=models.JSONField(blank=True, help_text="Scout's own Graph.to_dict() for this scan — every node and edge, not just the chain endpoints the envelope keeps. Null for every scan stored before this field existed: that is a normal, permanent state, not a backfill that is pending. Never returned by the detail or list serializer; the page polls those.", null=True),
        ),
    ]
