# Generated by Django 5.0.6 on 2026-09-10 11:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emulations', '__first__'),
        ('infrastructure', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Client-chosen label, for example 'Splunk production'.", max_length=120)),
                ('secret_encrypted', models.BinaryField(help_text="Fernet-encrypted HMAC secret. Never returned after creation; the client stores their own copy in the SIEM's webhook action.")),
                ('secret_hint', models.CharField(blank=True, help_text='Last few characters of the secret, so a user can tell two endpoints apart.', max_length=12)),
                ('enabled', models.BooleanField(default=True, help_text='Set False to reject posts without deleting the endpoint or its history.')),
                ('last_alert_at', models.DateTimeField(blank=True, help_text="When this endpoint last accepted an alert. Drives the 'integration not wired up' verdict, which must never be scored as a missed detection.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_endpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestedAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="When MayaTrail accepted the alert. Attribution uses this rather than fired_at, because the SIEM's clock is not ours to trust.")),
                ('fired_at', models.DateTimeField(blank=True, help_text='When the SIEM says the rule fired. Displayed, not used for attribution.', null=True)),
                ('rule_id', models.CharField(blank=True, db_index=True, help_text="Rule identifier from the SIEM. When the client deployed MayaTrail's rules this is the Sigma UUID, which matches a shipped rule exactly.", max_length=200)),
                ('rule_name', models.CharField(blank=True, max_length=400)),
                ('technique', models.CharField(blank=True, db_index=True, help_text='ATT&CK technique the alert is tagged with, upper-cased. The fallback match for a client running their own detections rather than ours.', max_length=32)),
                ('severity', models.CharField(blank=True, max_length=32)),
                ('raw', models.JSONField(blank=True, default=dict, help_text='The payload as posted, so a verdict can be traced to its evidence.')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='workflows.alertendpoint')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['endpoint', 'received_at'], name='workflows_i_endpoin_da5611_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emulation_type', models.CharField(help_text='Registry name of the emulation this workflow validates.', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deploying', 'Deploying infrastructure'), ('attacking', 'Running emulation'), ('awaiting_alerts', 'Waiting for SIEM alerts'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('detail', models.TextField(blank=True, help_text='Human-readable reason for the current status, set when a step fails.')),
                ('window_start', models.DateTimeField(blank=True, help_text='Attack start. Alerts before this belong to something else.', null=True)),
                ('window_end', models.DateTimeField(blank=True, help_text='Attack end. Alerts are attributed from window_start to alert_deadline.', null=True)),
                ('alert_deadline', models.DateTimeField(blank=True, db_index=True, help_text='When to stop waiting and score with whatever arrived. SIEMs evaluate on a schedule, so this is minutes after the attack, not seconds.', null=True)),
                ('report', models.JSONField(blank=True, help_text='Per-rule verdicts with the alert evidence behind each one.', null=True)),
                ('score', models.JSONField(blank=True, help_text='Detection coverage and integration health. Separate figures on purpose: a rule nothing exercised is a connection problem, not a detection failure, and blending them hides the actionable one.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('emulation_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to='emulations.emulationrun')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to=settings.AUTH_USER_MODEL)),
                ('stack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to='infrastructure.stack')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='workflows_w_owner_i_4f4ddc_idx')],
            },
        ),
    ]
