# Generated by Django 5.0.6 on 2026-09-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='failed_step',
            field=models.CharField(blank=True, help_text='Which step abandoned the run: deploy, attack, alerts or score. Recorded because only the code that gave up knows this. Inferring it afterwards from timestamps marked a failed deploy as successful and blamed the attack step, which had never run.', max_length=20),
        ),
    ]
