# Generated by Django 5.0.6 on 2026-09-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflowrun_failed_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='When the run should start. Null means immediately. A scheduled run holds at SCHEDULED until the beat tick that finds this time passed.', null=True),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('pending', 'Pending'), ('deploying', 'Deploying infrastructure'), ('attacking', 'Running emulation'), ('awaiting_alerts', 'Waiting for SIEM alerts'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
