# Generated by Django 5.0.6 on 2026-09-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_workflowrun_scheduled_for_alter_workflowrun_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the owner archived this run. Archiving hides a run from the run list and from coverage history without destroying it, and is reversible. Deletion is not offered for a completed run: its report and attributed alerts are the evidence behind past verdicts, and removing them would raise every reliability figure that counted them, so a rule could appear to improve because its failures were deleted.', null=True),
        ),
    ]
