# Generated by Django 5.0.6 on 2026-10-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_workflowrun_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='account_check',
            field=models.JSONField(blank=True, help_text="What the owner's AWS policies would refuse, as simulated just before deploy. Kept on the run so it describes the policies in force for this run. Shown beside the score and never part of it: only a refusal observed during the attack may explain a silent detection. Null on runs that predate the check.", null=True),
        ),
    ]
