# Generated by Django 5.0.6 on 2026-10-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_workflowrun_account_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowrun',
            name='account_check',
            field=models.JSONField(blank=True, help_text="What the owner's AWS policies would refuse, as simulated once the lab is deployed and just before the attack, for each identity the attack acts as. Runs from before 2026-10-05 were checked before deploy, as the connected role only. Kept on the run so it describes the policies in force for this run. Shown beside the score and never part of it: only a refusal observed during the attack may explain a silent detection. Null on runs that predate the check.", null=True),
        ),
    ]
