# Generated by Django 5.0.6 on 2026-09-16 22:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmulationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emulation_type', models.CharField(help_text="Emulation package identifier, e.g. 'scarleteel'.", max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('phase_current', models.IntegerField(default=0, help_text='Index of the phase currently executing (0 = not started).')),
                ('phase_total', models.IntegerField(default=0, help_text='Total number of phases for this emulation type.')),
                ('stdout', models.TextField(blank=True, help_text="Captured stdout from the attack module's run() function.")),
                ('stderr', models.TextField(blank=True, help_text="Captured stderr from the attack module's run() function.")),
                ('started_at', models.DateTimeField(blank=True, help_text='UTC timestamp when the Celery task began executing.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='UTC timestamp when the run reached a terminal status.', null=True)),
                ('detection_check', models.JSONField(blank=True, help_text='Detection coverage report for this run: per-rule verdict, counts and evidence, written by check_detection_coverage after the attack finishes. Null until the check runs, or when no archive is configured.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'emulation run',
                'verbose_name_plural': 'emulation runs',
                'db_table': 'emulation_runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
