# Generated by Django 5.0.6 on 2026-09-16 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emulations', '0001_initial'),
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emulationrun',
            name='stack',
            field=models.ForeignKey(help_text='The infrastructure stack this emulation ran against.', on_delete=django.db.models.deletion.CASCADE, related_name='emulation_runs', to='infrastructure.stack'),
        ),
    ]
