# Generated by Django 5.0.6 on 2026-09-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emulations', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emulationrun',
            name='detection_check',
        ),
    ]
