name: mayatrail-aws-lateral-movement-ec2-serial-console-send-ssh-public-key
runtime: python
description: Infrastructure for the aws_lateral_movement_ec2_serial_console_send_ssh_public_key atomic emulation.
