"""
MANIFEST for the Bypass ALB Authentication via Injected Listener Rule atomic emulation.

Ported from the pipeline emulation (campaign id aws.defense-evasion.elbv2-listener-auth-bypass-rule). The id/name is the
import-safe underscore form; the original id is in `aliases`. schema_version 3.
"""

MANIFEST = {
    'schema_version': 3,
    'name': 'aws_defense_evasion_elbv2_listener_auth_bypass_rule',
    'display_name': 'Bypass ALB Authentication via Injected Listener Rule',
    'description': "Simulates a compromised DevOps service account enumerating an ALB's listener and target-group ARNs (Describe* burst) and then calling elasticloadbalancingv2:CreateRule to insert a high-priority listener rule that forwards requests carrying a magic header straight to the protected target group, skipping the listener's authenticate action. Teardown deletes the injected rule.",
    'tier': 'atomic',
    'platform': 'aws',
    'added': '2026-08',
    'services': ['ELBv2', 'IAM'],
    'readiness': {'type': 'none'},
    'origin': 'mayatrail',
    'origin_label': 'ATOMIC TECHNIQUE',
    'tags': ['Defense Evasion', 'ELBv2'],
    'technique_count': 1,
    'severity': 'HIGH',
    'aliases': 'aws.defense-evasion.elbv2-listener-auth-bypass-rule',
    'attribution': 'Atomic adversary technique — no specific threat actor',
    'active_since': 'Atomic technique (MayaTrail pipeline)',
    'targets': 'AWS accounts running auth-protected ALB listeners with roles holding elasticloadbalancingv2:CreateRule',
    'incidents': ['Adan Alvarez — Manipulating AWS ALB listener rules research'],
    'attack_path': [{'phase': 1,
                     'name': 'Credential Access',
                     'techniques': [{'id': 'T1556', 'name': 'Modify Authentication Process'}]}],
    'mitre_mappings': [{'id': 'T1556',
                        'name': 'Modify Authentication Process',
                        'tactic': 'Credential Access',
                        'platform': 'AWS',
                        'description': 'elasticloadbalancingv2:CreateRule / ModifyRule adding a rule whose actions omit authenticate-* on an auth-protected listener'}],
    'references': [{'icon': '>',
                    'title': 'Rigging the Rules: Manipulating AWS ALB to Mine Sensitive Data',
                    'source': 'Adan Alvarez · medium.com',
                    'type': 'REFERENCE',
                    'color': 'cyan',
                    'url': 'https://medium.com/@adan.alvarez/rigging-the-rules-manipulating-aws-alb-to-mine-sensitive-data-20e33dbc4994'},
                   {'icon': '#',
                    'title': 'MITRE ATT&CK — T1556',
                    'source': 'MITRE ATT&CK · mitre.org',
                    'type': 'MITRE',
                    'color': 'purple',
                    'url': 'https://attack.mitre.org/techniques/T1556/'}],
    'phase_count': 1,
    'estimated_duration_minutes': 12,
    'estimated_cost_per_hour_usd': 0.03,
    'default_ttl_hours': 2,
    'total_resources': 34,
    'resources': {'ec2_count': 0, 'instance_types': []},
    'resource_costs': [],
}
