# Generated by Django 5.0.6 on 2026-09-11 18:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Display name, e.g. 'AMBERSQUID — our response'.", max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-safe form of the title. Derived on save; not unique on its own because two users may title a playbook the same.', max_length=220)),
                ('body', models.TextField(blank=True, default='', help_text='The playbook itself, as Markdown.')),
                ('summary', models.CharField(blank=True, default='', help_text='One-line description shown on the playbook card.', max_length=400)),
                ('source_emulation', models.CharField(blank=True, db_index=True, default='', help_text="Emulation package this playbook was forked from, e.g. 'ambersquid'. Empty when the playbook was authored from scratch.", max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=16)),
                ('visibility', models.CharField(choices=[('private', 'Private to the author'), ('organization', "Everyone in the author's organisation")], db_index=True, default='private', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The user who created this playbook.', on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'playbooks',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner', '-updated_at'], name='playbooks_owner_i_2ac93b_idx')],
            },
        ),
    ]
