# Generated by Django 5.0.6 on 2026-09-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='is_example',
            field=models.BooleanField(default=False, help_text='True for the starter playbooks seeded on signup. Purely a UI label and a signal that this is safe to delete; behaves like any other playbook otherwise.'),
        ),
    ]
