# Generated by Django 5.0.6 on 2026-09-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aws_audit_role_arn',
            field=models.CharField(blank=True, default='', help_text='Read-only IAM role the Attack Graph scan assumes. Separate from aws_role_arn on purpose: that role performs the writes emulations need, this one grants a single IAM read, so a security team can review and revoke IAM-graph access without touching emulations.', max_length=256),
        ),
    ]
