"""
MANIFEST for the Expose RDS Instance via ModifyDBInstance Public Access atomic emulation.

Ported from the pipeline emulation (campaign id aws.defense-evasion.rds-modify-public-access). The id/name is the
import-safe underscore form; the original id is in `aliases`. schema_version 3.
"""

MANIFEST = {
    'schema_version': 3,
    'name': 'aws_defense_evasion_rds_modify_public_access',
    'display_name': 'Expose RDS Instance via ModifyDBInstance Public Access',
    'description': 'Simulates an attacker with rds:ModifyDBInstance and ec2:AuthorizeSecurityGroupIngress flipping a private RDS instance to PubliclyAccessible=true and opening its security group ingress, making the database internet-reachable for a direct data pull. Teardown reverts both changes.',
    'tier': 'atomic',
    'platform': 'aws',
    'added': '2026-08',
    'services': ['RDS', 'EC2', 'IAM'],
    'readiness': {'type': 'none'},
    'origin': 'mayatrail',
    'origin_label': 'ATOMIC TECHNIQUE',
    'tags': ['Defense Evasion', 'RDS'],
    'technique_count': 1,
    'severity': 'HIGH',
    'aliases': 'aws.defense-evasion.rds-modify-public-access',
    'attribution': 'Atomic adversary technique — no specific threat actor',
    'active_since': 'Atomic technique (MayaTrail pipeline)',
    'targets': 'AWS accounts with private RDS instances and roles holding rds:ModifyDBInstance',
    'incidents': ['Elastic — AWS RDS DB instance made public detection'],
    'attack_path': [{'phase': 1,
                     'name': 'Defense Evasion',
                     'techniques': [{'id': 'T1562.007', 'name': 'Impair Defenses: Disable or Modify Cloud Firewall'}]}],
    'mitre_mappings': [{'id': 'T1562.007',
                        'name': 'Impair Defenses: Disable or Modify Cloud Firewall',
                        'tactic': 'Defense Evasion',
                        'platform': 'AWS',
                        'description': 'rds:ModifyDBInstance setting PubliclyAccessible=true, paired with ec2:AuthorizeSecurityGroupIngress opening the DB port'}],
    'references': [{'icon': '>',
                    'title': 'HackTricks — AWS RDS Post-Exploitation',
                    'source': 'HackTricks Cloud · cloud.hacktricks.wiki',
                    'type': 'REFERENCE',
                    'color': 'cyan',
                    'url': 'https://cloud.hacktricks.wiki/en/pentesting-cloud/aws-security/aws-post-exploitation/aws-rds-post-exploitation.html'},
                   {'icon': '>',
                    'title': 'Elastic — AWS RDS DB Instance Made Public',
                    'source': 'Elastic Security · elastic.co',
                    'type': 'REFERENCE',
                    'color': 'cyan',
                    'url': 'https://www.elastic.co/guide/en/security/current/aws-rds-db-instance-made-public.html'},
                   {'icon': '#',
                    'title': 'MITRE ATT&CK — T1562.007',
                    'source': 'MITRE ATT&CK · mitre.org',
                    'type': 'MITRE',
                    'color': 'purple',
                    'url': 'https://attack.mitre.org/techniques/T1562/007/'}],
    'phase_count': 1,
    'estimated_duration_minutes': 25,
    'estimated_cost_per_hour_usd': 0.02,
    'default_ttl_hours': 2,
    'total_resources': 0,
    'resources': {'ec2_count': 0, 'instance_types': []},
    'resource_costs': [],
}
