# Generated by Django 5.0.6 on 2026-06-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconnector',
            name='region',
            field=models.CharField(blank=True, default='', help_text="AWS region for Amazon Bedrock (e.g. 'us-east-1'). Required for the bedrock provider; unused by key-based providers.", max_length=32),
        ),
        migrations.AlterField(
            model_name='llmconnector',
            name='api_key_encrypted',
            field=models.BinaryField(blank=True, help_text="Fernet-encrypted provider API key. Never stored or returned in plaintext. Null for the bedrock provider, which authenticates via the user's assumed AWS role instead of a stored key.", null=True),
        ),
        migrations.AlterField(
            model_name='llmconnector',
            name='model',
            field=models.CharField(help_text="Provider model id, e.g. 'gpt-4o', 'claude-sonnet-4-6', or a Bedrock inference-profile id like 'us.anthropic.claude-3-5-sonnet-20241022-v2:0'.", max_length=128),
        ),
        migrations.AlterField(
            model_name='llmconnector',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('bedrock', 'Amazon Bedrock')], default='openai', max_length=32),
        ),
    ]
