# Generated by Django 5.0.6 on 2026-09-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_llmconnector_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconnector',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('anthropic', 'Anthropic'), ('bedrock', 'Amazon Bedrock')], default='openai', max_length=32),
        ),
    ]
