"""
MANIFEST for the Exfiltrate DynamoDB Table via Export to S3 atomic emulation.

Ported from the pipeline emulation (campaign id aws.exfiltration.dynamodb-export-to-s3). The id/name is the
import-safe underscore form; the original id is in `aliases`. schema_version 3.
"""

MANIFEST = {
    'schema_version': 3,
    'name': 'aws_exfiltration_dynamodb_export_to_s3',
    'display_name': 'Exfiltrate DynamoDB Table via Export to S3',
    'description': 'Simulates an attacker who holds a low-privilege IAM access key pivoting via sts:AssumeRole to a data-engineer role, then calling dynamodb:ExportTableToPointInTime on a PITR-enabled table to dump its full contents to an in-account attacker-owned S3 bucket — a quiet bulk-export path that never issues a Scan or Query.',
    'tier': 'atomic',
    'platform': 'aws',
    'added': '2026-08',
    'services': ['DynamoDB', 'S3', 'IAM'],
    'readiness': {'type': 'none'},
    'origin': 'mayatrail',
    'origin_label': 'ATOMIC TECHNIQUE',
    'tags': ['Exfiltration', 'DynamoDB'],
    'technique_count': 1,
    'severity': 'HIGH',
    'aliases': 'aws.exfiltration.dynamodb-export-to-s3',
    'attribution': 'Atomic adversary technique — no specific threat actor',
    'active_since': 'Atomic technique (MayaTrail pipeline)',
    'targets': 'AWS accounts with PITR-enabled DynamoDB tables and roles holding dynamodb:ExportTableToPointInTime',
    'incidents': ['3CoreSec — DynamoDB export exfiltration research'],
    'attack_path': [{'phase': 1,
                     'name': 'Collection',
                     'techniques': [{'id': 'T1530', 'name': 'Data from Cloud Storage'}]}],
    'mitre_mappings': [{'id': 'T1530',
                        'name': 'Data from Cloud Storage',
                        'tactic': 'Collection',
                        'platform': 'AWS',
                        'description': 'dynamodb:ExportTableToPointInTime writing a full table snapshot to an attacker-controlled S3 bucket'}],
    'references': [{'icon': '>',
                    'title': '3CoreSec — The undetectable way of exporting AWS DynamoDB',
                    'source': '3CoreSec Blog · blog.3coresec.com',
                    'type': 'REFERENCE',
                    'color': 'cyan',
                    'url': 'https://blog.3coresec.com/2020/04/the-undetectable-way-of-exporting-aws.html'},
                   {'icon': '>',
                    'title': 'HackTricks — AWS DynamoDB Post-Exploitation',
                    'source': 'HackTricks Cloud · cloud.hacktricks.wiki',
                    'type': 'REFERENCE',
                    'color': 'cyan',
                    'url': 'https://cloud.hacktricks.wiki/en/pentesting-cloud/aws-security/aws-post-exploitation/aws-dynamodb-post-exploitation.html'},
                   {'icon': '#',
                    'title': 'MITRE ATT&CK — T1530',
                    'source': 'MITRE ATT&CK · mitre.org',
                    'type': 'MITRE',
                    'color': 'purple',
                    'url': 'https://attack.mitre.org/techniques/T1530/'}],
    'phase_count': 1,
    'estimated_duration_minutes': 8,
    'estimated_cost_per_hour_usd': 0.0,
    'default_ttl_hours': 1,
    'total_resources': 32,
    'resources': {'ec2_count': 0, 'instance_types': []},
    'resource_costs': [],
}
