"""
Every ATT&CK ID and name a manifest ships is MITRE's own.

The MITRE tab renders `mitre_mappings[].id` and `mitre_mappings[].name` together
as a citation: the ID in a badge with the name directly beneath it.  A reader
takes that pair as "this is what MITRE calls this technique".  So a name that is
really a description of what the emulation does is a factual error shown to a
security engineer, not a style choice.  The manifest schema already has a slot
for the emulation-specific wording: `description`.

These tests check the pair against the bundled ATT&CK catalogue
(apps/metrics/mitre/catalog.json, regenerated by scripts/build_mitre_catalog.py).
Nothing here touches the network; the catalogue is checked in precisely so CI
stays deterministic and offline.

Four defect classes, each seen in review:

  1. An ID that does not exist.  contracts.py only proves the PARENT resolves,
     so an invented sub-technique number such as T1685.999 passes there and is
     caught here.
  2. A name that is not MITRE's name for that ID.
  3. A revoked ID.  These still resolve (the catalogue carries a revoked_map),
     so they never fail loudly, they just quietly land in the wrong heatmap row.
  4. A MITRE reference URL that does not match the ID it claims to document.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

from django.test import SimpleTestCase

from apps.emulations import registry as registry_wrapper
from apps.metrics.mitre import catalog

# backend/apps/metrics/tests/test_mitre_fidelity.py -> repo root is parents[4].
_REPO_ROOT = Path(__file__).resolve().parents[4]
_FALLBACK_EMULATIONS_DIR = _REPO_ROOT / "emulations"

# https://attack.mitre.org/techniques/T1685/002/ -> ("T1685", "002")
_MITRE_URL_RE = re.compile(
    r"attack\.mitre\.org/techniques/(T\d{4})(?:/(\d{3}))?/?", re.IGNORECASE
)


def _resolve_emulations_dir() -> Path:
    """Prefer EMULATIONS_BASE_DIR (Docker); fall back to the repo checkout."""
    env_dir = os.environ.get("EMULATIONS_BASE_DIR", "")
    if env_dir and Path(env_dir).is_dir():
        return Path(env_dir)
    return _FALLBACK_EMULATIONS_DIR


def _load_emulations(base_dir: Path):
    """Point the registry at base_dir and return the discovered catalogue."""
    os.environ["EMULATIONS_BASE_DIR"] = str(base_dir)
    registry_wrapper.reset_cache()
    return registry_wrapper.list_emulations()


def _mappings(entry: dict) -> list[dict]:
    """Return the manifest's mitre_mappings, tolerating a malformed value."""
    raw = entry.get("mitre_mappings")
    return [m for m in raw if isinstance(m, dict)] if isinstance(raw, list) else []


class MitreFidelityTests(SimpleTestCase):
    """Manifest ATT&CK citations match the bundled ATT&CK catalogue."""

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.entries = _load_emulations(_resolve_emulations_dir())

    def test_catalogue_carries_subtechnique_names(self):
        """
        The catalogue must ship sub-technique names.

        Without them every other check in this file silently degrades to a
        parent-only check, which is what let a wrong sub-technique name ship in
        the first place. Regenerate with scripts/build_mitre_catalog.py.
        """
        self.assertTrue(
            catalog.subtechniques(),
            "catalog.json has no 'subtechniques' key -- regenerate it with "
            "scripts/build_mitre_catalog.py so sub-technique IDs can be validated",
        )

    def test_every_technique_id_exists(self):
        """Every cited ID names a live technique or sub-technique."""
        bad = [
            f"{entry.get('name')}: {mapping.get('id')!r} is not a live ATT&CK ID"
            for entry in self.entries
            for mapping in _mappings(entry)
            if not catalog.is_known_exact(str(mapping.get("id", "")))
        ]
        self.assertEqual([], bad, "\n" + "\n".join(bad))

    def test_no_revoked_technique_ids(self):
        """
        No manifest cites a revoked ID.

        A revoked ID still resolves through the revoked_map, so it never fails
        loudly -- it just attributes the emulation to whatever the map points
        at, which for a fanned-out revocation can be the wrong parent.
        """
        revoked = catalog._catalog().get("revoked_map", {})
        bad = []
        for entry in self.entries:
            for mapping in _mappings(entry):
                tid = str(mapping.get("id", "")).strip()
                target = revoked.get(tid) or revoked.get(tid.split(".", 1)[0])
                if target:
                    bad.append(
                        f"{entry.get('name')}: {tid} is revoked, use {target}"
                    )
        self.assertEqual([], bad, "\n" + "\n".join(bad))

    def test_technique_names_are_mitres_own(self):
        """
        Each `name` is MITRE's name for that ID.

        Two spellings are accepted for a sub-technique, because MITRE itself
        uses both: the STIX bundle stores the leaf name ("Cloud Firewall") while
        attack.mitre.org titles the page with the qualified form ("Disable or
        Modify System Firewall: Cloud Firewall"). Either is a faithful citation,
        so neither is worth a mass rename.

        What is not accepted is a description of what the emulation does. That
        belongs in the mapping's `description`; putting it in `name` tells the
        reader MITRE calls the technique something it does not.
        """
        bad = []
        for entry in self.entries:
            for mapping in _mappings(entry):
                tid = str(mapping.get("id", "")).strip()
                leaf = catalog.official_name(tid)
                if leaf is None:
                    continue  # reported by test_every_technique_id_exists
                accepted = {leaf}
                if "." in tid:
                    parent = catalog.official_name(tid.split(".", 1)[0])
                    if parent:
                        accepted.add(f"{parent}: {leaf}")
                claimed = str(mapping.get("name", "")).strip()
                if claimed not in accepted:
                    expected = " or ".join(repr(a) for a in sorted(accepted))
                    bad.append(
                        f"{entry.get('name')}: {tid} name is {claimed!r}, "
                        f"MITRE calls it {expected}"
                    )
        self.assertEqual([], bad, "\n" + "\n".join(bad))

    def test_mitre_reference_urls_match_their_technique(self):
        """
        Every MITRE reference URL points at an ID the manifest actually cites.

        A stale URL survives the reference contract (which only checks that a
        URL is present and http(s)) while sending the reader to the wrong page.
        """
        bad = []
        for entry in self.entries:
            cited = {
                str(m.get("id", "")).strip().upper() for m in _mappings(entry)
            }
            for ref in entry.get("references") or []:
                if not isinstance(ref, dict):
                    continue
                match = _MITRE_URL_RE.search(str(ref.get("url", "")))
                if not match:
                    continue
                base, sub = match.group(1).upper(), match.group(2)
                url_id = f"{base}.{sub}" if sub else base
                if url_id not in cited:
                    bad.append(
                        f"{entry.get('name')}: reference URL documents {url_id}, "
                        f"which is not in mitre_mappings {sorted(cited)}"
                    )
        self.assertEqual([], bad, "\n" + "\n".join(bad))
