"""
MANIFEST for the Obtain AWS Creds via Cognito Unauthenticated Identity Pool atomic emulation.

Ported from the pipeline emulation (campaign id aws.initial-access.cognito-identity-pool-unauth-creds). The id/name is the
import-safe underscore form; the original id is in `aliases`. schema_version 3.
"""

MANIFEST = {
    'schema_version': 3,
    'name': 'aws_initial_access_cognito_identity_pool_unauth_creds',
    'display_name': 'Obtain AWS Creds via Cognito Unauthenticated Identity Pool',
    'description': 'Simulates an anonymous client calling cognito-identity:GetId then GetCredentialsForIdentity against an identity pool that allows unauthenticated access, receiving temporary AWS credentials for an over-permissioned unauth IAM role, and using them to read a target S3 bucket. The Cognito calls are issued unsigned so CloudTrail attributes them to the anonymous identity.',
    'tier': 'atomic',
    'platform': 'aws',
    'added': '2026-08',
    'services': ['Cognito', 'S3', 'IAM'],
    'readiness': {'type': 'none'},
    'origin': 'mayatrail',
    'origin_label': 'ATOMIC TECHNIQUE',
    'tags': ['Initial Access', 'Cognito'],
    'technique_count': 1,
    'severity': 'HIGH',
    'aliases': 'aws.initial-access.cognito-identity-pool-unauth-creds',
    'attribution': 'Atomic adversary technique — no specific threat actor',
    'active_since': 'Atomic technique (MayaTrail pipeline)',
    'targets': 'AWS accounts with Cognito identity pools that enable unauthenticated identities',
    'incidents': ['Hacking the Cloud — Cognito identity pool privilege research'],
    'attack_path': [{'phase': 1,
                     'name': 'Initial Access',
                     'techniques': [{'id': 'T1078.004', 'name': 'Valid Accounts: Cloud Accounts'}]}],
    'mitre_mappings': [{'id': 'T1078.004',
                        'name': 'Valid Accounts: Cloud Accounts',
                        'tactic': 'Initial Access',
                        'platform': 'AWS',
                        'description': 'cognito-identity:GetCredentialsForIdentity issuing AWS credentials for an over-permissioned unauthenticated role'}],
    'references': [{'icon': '>',
                    'title': 'Hacking the Cloud — Cognito Identity Pool Excessive Privileges',
                    'source': 'Hacking the Cloud · hackingthe.cloud',
                    'type': 'REFERENCE',
                    'color': 'cyan',
                    'url': 'https://hackingthe.cloud/aws/exploitation/cognito_identity_pool_excessive_privileges/'},
                   {'icon': '>',
                    'title': 'Hacking the Cloud — Cognito User Self-Signup',
                    'source': 'Hacking the Cloud · hackingthe.cloud',
                    'type': 'REFERENCE',
                    'color': 'cyan',
                    'url': 'https://hackingthe.cloud/aws/exploitation/cognito_user_self_signup/'},
                   {'icon': '#',
                    'title': 'MITRE ATT&CK — T1078.004',
                    'source': 'MITRE ATT&CK · mitre.org',
                    'type': 'MITRE',
                    'color': 'purple',
                    'url': 'https://attack.mitre.org/techniques/T1078/004/'}],
    'phase_count': 3,
    'estimated_duration_minutes': 8,
    'estimated_cost_per_hour_usd': 0.0,
    'default_ttl_hours': 1,
    'total_resources': 0,
    'resources': {'ec2_count': 0, 'instance_types': []},
    'resource_costs': [],
}
