"""
MANIFEST for the Exfiltrate via SNS External Subscription atomic emulation.

Ported from the pipeline emulation (campaign id aws.exfiltration.sns-external-subscription). The id/name is the
import-safe underscore form; the original id is in `aliases`. schema_version 3.
"""

MANIFEST = {
    'schema_version': 3,
    'name': 'aws_exfiltration_sns_external_subscription',
    'display_name': 'Exfiltrate via SNS External Subscription',
    'description': 'Simulates an attacker with sns:Subscribe attaching an attacker-controlled endpoint to an SNS topic that carries sensitive notifications, then calling sns:Publish to confirm the channel. In the sandbox the endpoint is an in-account SQS queue; real external delivery (email / HTTPS to C2) is documented but not performed.',
    'tier': 'atomic',
    'platform': 'aws',
    'added': '2026-08',
    'services': ['SNS', 'SQS', 'IAM'],
    'readiness': {'type': 'none'},
    'origin': 'mayatrail',
    'origin_label': 'ATOMIC TECHNIQUE',
    'tags': ['Exfiltration', 'SNS'],
    'technique_count': 1,
    'severity': 'MEDIUM',
    'aliases': 'aws.exfiltration.sns-external-subscription',
    'attribution': 'Atomic adversary technique — no specific threat actor',
    'active_since': 'Atomic technique (MayaTrail pipeline)',
    'targets': 'AWS accounts with SNS topics carrying sensitive events and roles holding sns:Subscribe',
    'incidents': ['Elastic Security Labs — AWS SNS abuse research'],
    'attack_path': [{'phase': 1,
                     'name': 'Exfiltration',
                     'techniques': [{'id': 'T1567', 'name': 'Exfiltration Over Web Service'}]}],
    'mitre_mappings': [{'id': 'T1567',
                        'name': 'Exfiltration Over Web Service',
                        'tactic': 'Exfiltration',
                        'platform': 'AWS',
                        'description': 'sns:Subscribe adding an external (email / HTTPS / cross-account) endpoint to a topic carrying sensitive messages'}],
    'references': [{'icon': '>',
                    'title': 'Elastic Security Labs — AWS SNS Abuse',
                    'source': 'Elastic Security Labs · elastic.co',
                    'type': 'REFERENCE',
                    'color': 'cyan',
                    'url': 'https://www.elastic.co/security-labs/aws-sns-abuse'},
                   {'icon': '>',
                    'title': 'HackTricks — AWS SQS/SNS Injection',
                    'source': 'HackTricks Cloud · cloud.hacktricks.wiki',
                    'type': 'REFERENCE',
                    'color': 'cyan',
                    'url': 'https://cloud.hacktricks.wiki/en/pentesting-cloud/aws-security/aws-post-exploitation/aws-sqs-post-exploitation/aws-sqs-sns-injection.html'},
                   {'icon': '#',
                    'title': 'MITRE ATT&CK — T1567',
                    'source': 'MITRE ATT&CK · mitre.org',
                    'type': 'MITRE',
                    'color': 'purple',
                    'url': 'https://attack.mitre.org/techniques/T1567/'}],
    'phase_count': 1,
    'estimated_duration_minutes': 3,
    'estimated_cost_per_hour_usd': 0.0,
    'default_ttl_hours': 1,
    'total_resources': 0,
    'resources': {'ec2_count': 0, 'instance_types': []},
    'resource_costs': [],
}
