name: mayatrail-aws-credential-access-ssm-retrieve-securestring-parameters
runtime: python
description: Infrastructure for the aws_credential_access_ssm_retrieve_securestring_parameters atomic emulation.
