# Generated by Django 5.0.6 on 2026-09-16 22:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Pulumi stack name, e.g. dev-himan10', max_length=128, unique=True)),
                ('region', models.CharField(default='us-east-1', help_text="AWS region for this stack. Defaults to us-east-1 so an emulation's API calls land in the same region the detection notifier watches; regional events written elsewhere never reach the archive.", max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deploying', 'Deploying'), ('ready', 'Ready'), ('destroying', 'Destroying'), ('refreshing', 'Refreshing'), ('failed', 'Failed'), ('ec2_booting', 'EC2 Booting'), ('ready_for_attack', 'Ready for Attack'), ('attacking', 'Attacking'), ('attack_complete', 'Attack Complete'), ('destroyed', 'Destroyed')], db_index=True, default='pending', max_length=20)),
                ('outputs', models.JSONField(blank=True, default=dict, help_text='Pulumi stack outputs as returned after a successful deploy.')),
                ('emulation_type', models.CharField(blank=True, default='', help_text="Identifies the emulation package for enterprise stacks (e.g. 'scarleteel', 'apt29'). Empty for demo/generic stacks.", max_length=64)),
                ('task_id', models.CharField(blank=True, default='', help_text='Celery task ID of the most recent deploy operation. Used by the progress endpoint to read live deployment state from Redis.', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, help_text="Auto-destroy deadline for enterprise stacks. Celery Beat destroys the stack when this timestamp is exceeded. Set at deploy time from the emulation MANIFEST's default_ttl_hours.", null=True)),
                ('last_logs', models.JSONField(blank=True, default=list, help_text="Captured Pulumi output for the most recent deploy/destroy/refresh, as a list of {'t': ISO-8601 timestamp, 'line': str}. Only the most recent run is retained; overwritten on each operation.")),
                ('last_error', models.TextField(blank=True, default='', help_text='Failure reason from the most recent operation (truncated). Empty when the last operation succeeded.')),
                ('resource_summary', models.JSONField(blank=True, default=dict, help_text="Actual deployed-resource inventory derived from the Pulumi state on the last successful deploy/refresh. Shape: {'total': int, 'by_type': {<service>: count}, 'resources': [{'name': str, 'type': str}]}. Empty before first deploy.")),
                ('status_history', models.JSONField(blank=True, default=list, help_text="Every status this stack has entered, oldest first, as [{'status': str, 'at': ISO-8601, 'detail': str}]. Appended by transition_to. Recorded because status is overwritten in place and updated_at moves on every save, so without this there is no way to tell how long a deploy spent in any phase, which is the question a stuck deploy actually raises.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'stack',
                'verbose_name_plural': 'stacks',
                'db_table': 'stacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
