# Generated by Django 5.0.6 on 2026-09-16 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='owner',
            field=models.ForeignKey(help_text='User who created this stack.', on_delete=django.db.models.deletion.CASCADE, related_name='stacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
