"""
Runtime loader and normalisation helpers for the bundled MITRE ATT&CK catalogue.

The catalogue (catalog.json, generated by scripts/build_mitre_catalog.py) is the
single source of truth for:

  * the APT Coverage Score denominator (total technique-level Enterprise count),
  * the canonical tactic ordering and per-technique tactic placement used by the
    MITRE coverage heatmap.

All dashboard code that needs to reason about ATT&CK techniques must go through
normalize_technique() so that two concerns are handled consistently in one place:

  1. Sub-technique roll-up — "T1552.005" is counted as its parent "T1552",
     matching the technique-level coverage decision.
  2. Revoked-ID forward resolution — emulation manifests authored against an
     older ATT&CK release may reference a technique MITRE has since revoked
     (e.g. T1562 -> T1685).  The catalogue's revoked_map remaps these so old
     content keeps scoring against a live technique.

The catalogue is loaded once and cached in-process.  It is static data shipped
with the codebase, so no reload mechanism is needed at runtime; regenerate the
JSON and redeploy to upgrade ATT&CK versions.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

_CATALOG_PATH = Path(__file__).resolve().parent / "catalog.json"


@lru_cache(maxsize=1)
def _catalog() -> dict[str, Any]:
    """Load and cache catalog.json from disk."""
    return json.loads(_CATALOG_PATH.read_text(encoding="utf-8"))


@lru_cache(maxsize=1)
def _technique_index() -> dict[str, dict[str, Any]]:
    """Return a mapping of technique ID -> technique entry for O(1) lookups."""
    return {t["id"]: t for t in _catalog()["techniques"]}


def attack_version() -> str:
    """Return the ATT&CK release version the bundled catalogue was built from."""
    return _catalog().get("attack_version", "unknown")


def technique_count() -> int:
    """
    Return the coverage-score denominator: the number of technique-level
    Enterprise techniques in the catalogue.
    """
    return _catalog()["technique_count"]


def tactics() -> list[dict[str, str]]:
    """Return the ordered list of ATT&CK tactics (matrix column order)."""
    return _catalog()["tactics"]


def techniques() -> list[dict[str, Any]]:
    """
    Return the full list of catalogue techniques.

    Each entry is {"id", "name", "tactics": [shortname, ...]}.  Used by the
    MITRE heatmap to render every technique cell, covered or not.
    """
    return _catalog()["techniques"]


def normalize_technique(technique_id: str) -> str:
    """
    Normalise a raw technique ID to a catalogue-comparable parent ID.

    Applies sub-technique roll-up first ("T1552.005" -> "T1552"), then forwards
    revoked IDs to their current replacement ("T1562" -> "T1685").

    The returned ID is not guaranteed to exist in the catalogue — callers that
    need that guarantee should follow up with is_known().  This keeps the
    function total (never raises) so aggregation code can normalise freely.

    Args:
        technique_id: A raw ATT&CK technique or sub-technique ID, e.g.
                      "T1552.005".  Surrounding whitespace is tolerated.

    Returns:
        The normalised parent technique ID.
    """
    parent = technique_id.strip().split(".", 1)[0]
    return _catalog().get("revoked_map", {}).get(parent, parent)


def is_known(technique_id: str) -> bool:
    """
    Return True if the technique ID resolves to a live catalogue technique.

    The ID is normalised (roll-up + revoked-map) before the membership check.
    """
    return normalize_technique(technique_id) in _technique_index()


def technique_name(technique_id: str) -> str | None:
    """Return the catalogue display name for a technique ID, or None if unknown."""
    entry = _technique_index().get(normalize_technique(technique_id))
    return entry["name"] if entry else None


def tactics_for(technique_id: str) -> list[str]:
    """
    Return the catalogue tactic shortnames a technique belongs to.

    Placement is taken from the catalogue (authoritative), never from manifest
    tactic labels, so the heatmap stays correct as ATT&CK reorganises tactics.

    Returns an empty list for unknown techniques.
    """
    entry = _technique_index().get(normalize_technique(technique_id))
    return list(entry["tactics"]) if entry else []
