"""
Display names for the AWS service prefixes that appear in policy actions.

An action reads "kms:ScheduleKeyDeletion"; the prefix before the colon is the
service. Upper-casing it gives "KMS", which is right, but the same rule turns
"elasticmapreduce" into "ELASTICMAPREDUCE" and "cognito-idp" into
"COGNITO-IDP". This table holds the prefixes whose display name a reader would
not guess, so the library labels a policy the way AWS names the service.

Prefixes absent from the table fall back to upper case, which is correct for
the short acronym services (ec2, iam, sts, rds) and harmless for the rest.
"""

SERVICE_LABELS = {
    "account": "Account",
    "acm-pca": "ACM PCA",
    "aoss": "OpenSearch Serverless",
    "apigateway": "API Gateway",
    "applicationinsights": "App Insights",
    "apprunner": "App Runner",
    "appstream": "AppStream",
    "aps": "Prometheus",
    "athena": "Athena",
    "auditmanager": "Audit Manager",
    "aws-marketplace": "Marketplace",
    "b2bi": "B2B Data Interchange",
    "backup": "Backup",
    "bedrock": "Bedrock",
    "bedrock-agentcore": "Bedrock AgentCore",
    "bedrock-mantle": "Bedrock",
    "billing": "Billing",
    "cassandra": "Keyspaces",
    "cloud9": "Cloud9",
    "cloudformation": "CloudFormation",
    "cloudhsm": "CloudHSM",
    "cloudshell": "CloudShell",
    "cloudtrail": "CloudTrail",
    "cloudwatch": "CloudWatch",
    "codeartifact": "CodeArtifact",
    "codebuild": "CodeBuild",
    "codestar-connections": "CodeConnections",
    "cognito-identity": "Cognito",
    "cognito-idp": "Cognito",
    "comprehendmedical": "Comprehend Medical",
    "compute-optimizer": "Compute Optimizer",
    "config": "Config",
    "connect": "Connect",
    "datasync": "DataSync",
    "detective": "Detective",
    "directconnect": "Direct Connect",
    "discovery": "App Discovery",
    "dms": "DMS",
    "ds": "Directory Service",
    "ds-data": "Directory Service",
    "dsql": "Aurora DSQL",
    "dynamodb": "DynamoDB",
    "ebs": "EBS",
    "ec2": "EC2",
    "ecr": "ECR",
    "ecs": "ECS",
    "eks": "EKS",
    "elasticache": "ElastiCache",
    "elasticfilesystem": "EFS",
    "elasticmapreduce": "EMR",
    "es": "OpenSearch",
    "events": "EventBridge",
    "firehose": "Firehose",
    "fis": "FIS",
    "gamelift": "GameLift",
    "glacier": "S3 Glacier",
    "globalaccelerator": "Global Accelerator",
    "glue": "Glue",
    "guardduty": "GuardDuty",
    "healthlake": "HealthLake",
    "iam": "IAM",
    "identitystore": "Identity Store",
    "imagebuilder": "Image Builder",
    "invoicing": "Invoicing",
    "iotfleetwise": "IoT FleetWise",
    "iottwinmaker": "IoT TwinMaker",
    "iotwireless": "IoT Wireless",
    "kafka": "MSK",
    "kinesis": "Kinesis",
    "kinesisanalytics": "Kinesis Analytics",
    "kms": "KMS",
    "lakeformation": "Lake Formation",
    "lambda": "Lambda",
    "lex": "Lex",
    "logs": "CloudWatch Logs",
    "macie2": "Macie",
    "medical-imaging": "HealthImaging",
    "network-firewall": "Network Firewall",
    "oam": "CloudWatch OAM",
    "omics": "HealthOmics",
    "organizations": "Organizations",
    "payment-cryptography": "Payment Cryptography",
    "payments": "Payments",
    "polly": "Polly",
    "pricing": "Pricing",
    "ram": "RAM",
    "rbin": "Recycle Bin",
    "rds": "RDS",
    "redshift": "Redshift",
    "redshift-serverless": "Redshift Serverless",
    "rekognition": "Rekognition",
    "rolesanywhere": "Roles Anywhere",
    "route53": "Route 53",
    "route53domains": "Route 53 Domains",
    "s3": "S3",
    "sagemaker": "SageMaker",
    "savingsplans": "Savings Plans",
    "scheduler": "EventBridge Scheduler",
    "schemas": "EventBridge Schemas",
    "secretsmanager": "Secrets Manager",
    "securityhub": "Security Hub",
    "serverlessrepo": "Serverless Repo",
    "servicecatalog": "Service Catalog",
    "servicediscovery": "Cloud Map",
    "servicequotas": "Service Quotas",
    "ses": "SES",
    "signin": "Sign-in",
    "sms-voice": "Pinpoint SMS",
    "sns": "SNS",
    "sqs": "SQS",
    "ssm": "Systems Manager",
    "ssm-contacts": "SSM Contacts",
    "ssm-incidents": "SSM Incidents",
    "sso": "IAM Identity Center",
    "states": "Step Functions",
    "storagegateway": "Storage Gateway",
    "sts": "STS",
    "tax": "Tax Settings",
    "textract": "Textract",
    "transcribe": "Transcribe",
    "transfer": "Transfer Family",
    "workmail": "WorkMail",
    "workspaces": "WorkSpaces",
}


def label_for(prefix: str) -> str:
    """
    Return the display name for an AWS service prefix.

    Args:
        prefix: The part of an action before the colon, e.g. "elasticmapreduce".

    Returns:
        The mapped display name, or the prefix upper-cased when unmapped.
    """
    return SERVICE_LABELS.get(prefix, prefix.upper())
