"""
MANIFEST for the Neuter WAFv2 Web ACL by Inserting a Magic-Header Allow Rule atomic emulation.

Ported from the pipeline emulation (campaign id aws.defense-evasion.wafv2-disable-web-acl). The id/name is the
import-safe underscore form; the original id is in `aliases`. schema_version 3.
"""

MANIFEST = {
    'schema_version': 3,
    'name': 'aws_defense_evasion_wafv2_disable_web_acl',
    'display_name': 'Neuter WAFv2 Web ACL by Inserting a Magic-Header Allow Rule',
    'description': 'Simulates a compromised over-permissioned WAF operator using wafv2:UpdateWebACL to prepend a priority-0 ByteMatch ALLOW rule that short-circuits any request carrying a magic header (e.g. X-Bypass: <secret>) straight past an AWS managed rule group. The full existing config and LockToken are round-tripped so the managed rules are preserved and the WAF still appears intact.',
    'tier': 'atomic',
    'platform': 'aws',
    'added': '2026-08',
    'services': ['WAF', 'IAM'],
    'readiness': {'type': 'none'},
    'origin': 'mayatrail',
    'origin_label': 'ATOMIC TECHNIQUE',
    'tags': ['Defense Evasion', 'WAF'],
    'technique_count': 1,
    'severity': 'HIGH',
    'aliases': 'aws.defense-evasion.wafv2-disable-web-acl',
    'attribution': 'Atomic adversary technique — no specific threat actor',
    'active_since': 'Atomic technique (MayaTrail pipeline)',
    'targets': 'AWS accounts with regional WAFv2 Web ACLs and over-broad wafv2:UpdateWebACL grants',
    'incidents': ['Sysdig — Fuzzing and Bypassing the AWS WAF'],
    'attack_path': [{'phase': 1,
                     'name': 'Defense Evasion',
                     'techniques': [{'id': 'T1686.001', 'name': 'Disable or Modify System Firewall: Cloud Firewall'}]}],
    'mitre_mappings': [{'id': 'T1686.001',
                        'name': 'Disable or Modify System Firewall: Cloud Firewall',
                        'tactic': 'Defense Evasion',
                        'platform': 'AWS',
                        'description': 'wafv2:UpdateWebACL prepending a low-priority Allow rule (ByteMatch on a request header) ahead of a managed rule group'}],
    'references': [{'icon': '>',
                    'title': 'AWS — UpdateWebACL API Reference',
                    'source': 'AWS Documentation · docs.aws.amazon.com',
                    'type': 'REFERENCE',
                    'color': 'cyan',
                    'url': 'https://docs.aws.amazon.com/waf/latest/APIReference/API_UpdateWebACL.html'},
                   {'icon': '>',
                    'title': 'Sysdig — Fuzzing and Bypassing the AWS WAF',
                    'source': 'Sysdig · sysdig.com',
                    'type': 'REFERENCE',
                    'color': 'cyan',
                    'url': 'https://www.sysdig.com/blog/fuzzing-and-bypassing-the-aws-waf'},
                   {'icon': '#',
                    'title': 'MITRE ATT&CK — T1686.001',
                    'source': 'MITRE ATT&CK · mitre.org',
                    'type': 'MITRE',
                    'color': 'purple',
                    'url': 'https://attack.mitre.org/techniques/T1686/001/'}],
    'phase_count': 1,
    'estimated_duration_minutes': 3,
    'estimated_cost_per_hour_usd': 0.0,
    'default_ttl_hours': 1,
    'total_resources': 10,
    'resources': {'ec2_count': 0, 'instance_types': []},
    'resource_costs': [],
}
