"""
MANIFEST for the Poison CI/CD by Injecting a CodePipeline Stage atomic emulation.

Ported from the pipeline emulation (campaign id aws.execution.codepipeline-inject-stage). The id/name is the
import-safe underscore form; the original id is in `aliases`. schema_version 3.
"""

MANIFEST = {
    'schema_version': 3,
    'name': 'aws_execution_codepipeline_inject_stage',
    'display_name': 'Poison CI/CD by Injecting a CodePipeline Stage',
    'description': "Simulates an attacker with a compromised CI/CD service role calling codepipeline:GetPipeline to read the current definition, then codepipeline:UpdatePipeline to inject a malicious CodeBuild action that runs attacker-controlled commands with the pipeline's service role on the next execution. The injected step is reverted on teardown.",
    'tier': 'atomic',
    'platform': 'aws',
    'added': '2026-08',
    'services': ['CodePipeline', 'CodeBuild', 'IAM'],
    'readiness': {'type': 'none'},
    'origin': 'mayatrail',
    'origin_label': 'ATOMIC TECHNIQUE',
    'tags': ['Execution', 'CodePipeline'],
    'technique_count': 1,
    'severity': 'HIGH',
    'aliases': 'aws.execution.codepipeline-inject-stage',
    'attribution': 'Atomic adversary technique — no specific threat actor',
    'active_since': 'Atomic technique (MayaTrail pipeline)',
    'targets': 'AWS accounts running CodePipeline with roles holding codepipeline:UpdatePipeline',
    'incidents': ['OWASP Top 10 CI/CD Security Risks — Poisoned Pipeline Execution'],
    'attack_path': [{'phase': 1,
                     'name': 'Initial Access',
                     'techniques': [{'id': 'T1195', 'name': 'Supply Chain Compromise'}]}],
    'mitre_mappings': [{'id': 'T1195',
                        'name': 'Supply Chain Compromise',
                        'tactic': 'Initial Access',
                        'platform': 'AWS',
                        'description': "codepipeline:UpdatePipeline inserting a build action / altering an action's role to run attacker commands under the pipeline service role"}],
    'references': [{'icon': '>',
                    'title': 'OWASP — CICD-SEC-04: Poisoned Pipeline Execution',
                    'source': 'OWASP · owasp.org',
                    'type': 'REFERENCE',
                    'color': 'cyan',
                    'url': 'https://owasp.org/www-project-top-10-ci-cd-security-risks/CICD-SEC-04-Poisoned-Pipeline-Execution'},
                   {'icon': '>',
                    'title': 'The Hacker News — AWS CodeBuild misconfiguration',
                    'source': 'The Hacker News · thehackernews.com',
                    'type': 'REFERENCE',
                    'color': 'cyan',
                    'url': 'https://thehackernews.com/2026/01/aws-codebuild-misconfiguration-exposed.html'},
                   {'icon': '#',
                    'title': 'MITRE ATT&CK — T1195',
                    'source': 'MITRE ATT&CK · mitre.org',
                    'type': 'MITRE',
                    'color': 'purple',
                    'url': 'https://attack.mitre.org/techniques/T1195/'}],
    'phase_count': 3,
    'estimated_duration_minutes': 12,
    'estimated_cost_per_hour_usd': 0.0,
    'default_ttl_hours': 2,
    'total_resources': 0,
    'resources': {'ec2_count': 0, 'instance_types': []},
    'resource_costs': [],
}
