# Generated by Django 5.0.6 on 2026-09-12 15:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthoredDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Display name, e.g. 'CloudTrail StopLogging outside change window'.", max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('technique_id', models.CharField(blank=True, db_index=True, default='', help_text="Primary MITRE technique this rule targets, e.g. 'T1562.008'.", max_length=32)),
                ('sigma', models.TextField(blank=True, default='', help_text='The detection rule, as Sigma YAML.')),
                ('summary', models.CharField(blank=True, default='', help_text='One-line description shown on the rule card.', max_length=400)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=16)),
                ('visibility', models.CharField(choices=[('private', 'Private to the author'), ('organization', "Everyone in the author's organisation")], db_index=True, default='private', max_length=16)),
                ('origin', models.CharField(choices=[('manual', 'Written by hand'), ('generated', 'Drafted by AI')], default='manual', max_length=16)),
                ('last_fidelity', models.FloatField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The user who created this rule.', on_delete=django.db.models.deletion.CASCADE, related_name='authored_detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authored_detections',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner', '-updated_at'], name='authored_de_owner_i_080896_idx')],
            },
        ),
    ]
